
# all is used for game since we compile Game.cpp by default
all: 
		g++ Game.cpp Player.cpp Board.cpp Point.cpp Move.cpp Operation.cpp -o game

gameDebug:
		g++ -g Game.cpp Player.cpp Board.cpp Point.cpp Move.cpp Operation.cpp -o game

board:
		g++ Board.cpp Point.cpp 

clean:
	rm -rf game		



