all: 
		g++ -std=c++11 -Ofast -march=native Ai.cpp Tree.cpp Game.cpp Huerisitic.cpp Move.cpp Point.cpp Node.cpp Board.cpp Operation.cpp Player.cpp
aiNormal: 
		g++ Ai.cpp Tree.cpp Game.cpp Huerisitic.cpp Move.cpp Point.cpp Node.cpp Board.cpp Operation.cpp Player.cpp 

aiDebug:
		g++ -g Ai.cpp Tree.cpp Game.cpp Huerisitic.cpp Move.cpp Point.cpp Node.cpp Board.cpp Operation.cpp Player.cpp 

board:
		g++ Board.cpp Point.cpp 

clean:
	rm -rf a.out	
