
# all is used for game since we compile Game.cpp by default
all: 
		g++ Ai.cpp Tree.cpp Game.cpp Huerisitic.cpp Move.cpp Point.cpp Node.cpp Board.cpp Operation.cpp Player.cpp 

allDebug:
		g++ -g Ai.cpp Tree.cpp Game.cpp Huerisitic.cpp Move.cpp Point.cpp Node.cpp Board.cpp Operation.cpp Player.cpp 

board:
		g++ Board.cpp Point.cpp 

clean:
	rm -rf a.out		



